### ISSUE TITLE
Error '500 - JHtmlIcon::email not found.' when plugin Content - Load ETE is activated

### ISSUE THREAD

**Issue by peterhulst** [Theophilix/event-table-edit#187]
Hello,

When the plugin 'Content - Load ETE' is activated an error: 500 - JHtmlIcon::email not found. is generated.
Used in Joomla 3.9.25.

This also happens when the plugin is not selected in an article.

Regards,
Peter

**Comment by Theophilix** [comment]
This will be fixed soon.

**Comment by Theophilix** [comment]
Fixed in 4.8.8 version.

**Comment by Theophilix** [comment]
We have to fix this!

**Comment by Theophilix** [comment]
Nevermind, can't use it anyway.
Installing it broke my site immediately...  "JHtmlIcon::email not found."
Uninstalling it fixed the problem immediately...

_Originally posted by @Wikt0ri0 in https://github.com/Theophilix/event-table-edit/issues/192#issuecomment-903320359_

**Comment by peterhulst** [comment]
Hello,

Today I have given it a try again. 
However: version 4.8.8 gives immediately:
500 - JHtmlIcon::email not found.
and breaks my side (again).

So it is not solved yet. A pitty.

Regards,
Peter

**Comment by Theophilix** [comment]
Please use newest ETE: https://github.com/Theophilix/EventTableEdit
This version is not supported anymore.

**Comment by peterhulst** [comment]
I know it that there is a new version, but I am still on Joomla 3 and I reported the bug for Joomla 3. 
So there is no solution for Joomla 3?  
(The new ETE version can not be used in Joomla 3).

Regards

**Comment by Theophilix** [comment]
Please describe your problem more accurately. I talked to @vkrahu but he couldn't reproduce the error. Which Joomla version do you use, when does the error happen exactly? When installing ETE? What is your PHP Version?

**Comment by peterhulst** [comment]
Hello,
System details:  Joomla 3.10.9, PHP 7.4.26.
Component Event  Table Edit: 4.8.8
Plugin Content- Load ETE: 1.0.0
Template: protostar or purity_iii (dump below is with purity_iii, but also with protostar the crash is there).

Installation: no problem. Administator site works perfect. No table is defined.

Frontend: when the website is displayed with the Content- Load ETE **enabled**, directly a crash:
500 - JHtmlIcon::email not found.
Call stack
#	Function	Location
1	()	JROOT/libraries/src/HTML/HTMLHelper.php:137
2	Joomla\CMS\HTML\HTMLHelper::_()	JROOT/plugins/system/t3/base-bs3/html/layouts/joomla/content/icons.php:30
3	include()	JROOT/plugins/system/t3/includes/core/t3.php(525) : eval()'d code:125
4	Joomla\CMS\Layout\_FileLayout->render()	JROOT/libraries/src/Layout/LayoutHelper.php:73
5	Joomla\CMS\Layout\LayoutHelper::render()	JROOT/templates/purity_iii/html/com_content/featured/default_item.php:48
6	include()	JROOT/libraries/src/MVC/View/HtmlView.php:701
7	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/templates/purity_iii/html/com_content/featured/default.php:76
8	include()	JROOT/libraries/src/MVC/View/HtmlView.php:701
9	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:230
10	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/components/com_content/views/featured/view.html.php:164
11	ContentViewFeatured->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:664
12	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/components/com_content/controller.php:118
13	ContentController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:702
14	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/components/com_content/content.php:43
15	require_once()	JROOT/libraries/src/Component/ComponentHelper.php:402
16	Joomla\CMS\Component\ComponentHelper::executeComponent()	JROOT/libraries/src/Component/ComponentHelper.php:377
17	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:194
18	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:233
19	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:225
20	Joomla\CMS\Application\CMSApplication->execute()	JROOT/index.php:49

When the Content- Load ETE is **DISABLED** the website works perfect.

Regards,
Peter
